# Generated by Django 4.0.4 on 2022-11-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_links_link_rename_uploads_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='latitude',
            field=models.FloatField(default=48.1374932),
        ),
        migrations.AddField(
            model_name='upload',
            name='longitude',
            field=models.FloatField(default=11.5754485),
        ),
    ]
