# Generated by Django 4.1.3 on 2022-11-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_upload_latitude_upload_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='postId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upload',
            name='latitude',
            field=models.FloatField(default=48.2625728),
        ),
        migrations.AlterField(
            model_name='upload',
            name='longitude',
            field=models.FloatField(default=11.6677239),
        ),
    ]
